# Generated by Django 5.2.15 on 2026-06-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('LABORATORY', 'Laboratory'), ('IMPORTER', 'Importer'), ('DISTRIBUTOR', 'Distributor'), ('MANUFACTURER', 'Manufacturer'), ('SERVICE', 'Service')], default='DISTRIBUTOR', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
