# Generated by Django 5.2.15 on 2026-07-01 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_company_code'),
        ('mdm', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='iam.company')),
            ],
            options={
                'verbose_name': 'Unit Of Measure',
                'verbose_name_plural': 'Units Of Measure',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uq_uom_code')],
            },
        ),
    ]
