# Generated by Django 5.2.15 on 2026-07-01 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_company_code'),
        ('mdm', '0005_unitofmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('internal_code', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('MEDICINE', 'Medicine'), ('MEDICAL_SUPPLY', 'Medical Supply'), ('COSMETIC', 'Cosmetic'), ('EQUIPMENT', 'Equipment'), ('SERVICE', 'Service')], default='MEDICINE', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('health_registration', models.CharField(blank=True, max_length=100)),
                ('requires_batch', models.BooleanField(default=False)),
                ('requires_expiration', models.BooleanField(default=False)),
                ('requires_serial', models.BooleanField(default=False)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('maximum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_products', to='mdm.unitofmeasure')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='mdm.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='mdm.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='iam.company')),
                ('purchase_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_products', to='mdm.unitofmeasure')),
                ('sales_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_products', to='mdm.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_primary', models.BooleanField(default=False)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='mdm.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mdm.supplier')),
            ],
            options={
                'verbose_name': 'Product Supplier',
                'verbose_name_plural': 'Product Suppliers',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'internal_code'), name='uq_product_internal_code'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(fields=('product', 'supplier'), name='uq_product_supplier'),
        ),
    ]
