# Generated by Django 5.2.15 on 2026-07-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_company_code'),
        ('mdm', '0006_product_productsupplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MEDICINE', 'Medicine'), ('MEDICAL_SUPPLY', 'Medical Supply'), ('COSMETIC', 'Cosmetic'), ('EQUIPMENT', 'Equipment'), ('SERVICE', 'Service'), ('RAW_MATERIAL', 'Raw Material')], default='MEDICINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='uq_product_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('company', 'barcode'), name='uq_product_barcode'),
        ),
    ]
