# Generated by Django 5.2.15 on 2026-07-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchasereceipt_purchasereceiptline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={'ordering': ['purchase_order', 'id'], 'verbose_name': 'Purchase Order Line', 'verbose_name_plural': 'Purchase Order Lines'},
        ),
    ]
