# Generated by Django 5.2.15 on 2026-07-03 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_accountspayable_supplierpayment_and_more'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount'),
        ),
    ]
