# Generated by Django 5.2.15 on 2026-07-02 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_company_code'),
        ('inventory', '0001_initial'),
        ('mdm', '0007_product_active_ingredient_product_concentration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('average_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='iam.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='mdm.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='inventory.warehouse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'warehouse', 'product'), name='uq_stock_balance')],
            },
        ),
    ]
