# Generated by Django 5.2.15 on 2026-07-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytransfer_inventorytransferline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransfer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
