# Generated by Django 5.2.15 on 2026-06-30 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_parameter'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='iam.company'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='uq_company_parameter'),
        ),
    ]
