# Generated by Django 5.2.15 on 2026-06-30 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parameter_company_alter_parameter_category_and_more'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='iam.company'),
        ),
        migrations.CreateModel(
            name='Numeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('fiscal_year', models.IntegerField()),
                ('prefix', models.CharField(max_length=20)),
                ('current_number', models.IntegerField(default=0)),
                ('padding', models.IntegerField(default=6)),
                ('separator', models.CharField(default='-', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerations', to='iam.company')),
            ],
            options={
                'verbose_name': 'Numeration',
                'verbose_name_plural': 'Numerations',
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type', 'fiscal_year'), name='uq_company_document_year')],
            },
        ),
    ]
